from typing import Dict, NamedTuple

from BaseClasses import Item, ItemClassification


class CivVItem(Item):
    game: str = "Civilization V"

class CivVItemData(NamedTuple):
    id: int = None
    type: ItemClassification = ItemClassification.filler

item_table: Dict[str, CivVItemData] = {
    "Pottery":              CivVItemData(1, type=ItemClassification.progression),
    "Animal Husbandry":     CivVItemData(2, type=ItemClassification.progression),
    "Archery":              CivVItemData(3, type=ItemClassification.progression),
    "Mining":               CivVItemData(4, type=ItemClassification.progression),
    "Sailing":              CivVItemData(5, type=ItemClassification.progression),
    "Calendar":             CivVItemData(6, type=ItemClassification.progression),
    "Writing":              CivVItemData(7, type=ItemClassification.progression),
    "Trapping":             CivVItemData(8, type=ItemClassification.progression),
    "The Wheel":            CivVItemData(9, type=ItemClassification.progression),
    "Masonry":              CivVItemData(10, type=ItemClassification.progression),
    "Bronze Working":        CivVItemData(11, type=ItemClassification.progression),
    "Optics":               CivVItemData(12, type=ItemClassification.progression),
    "Horseback Riding":     CivVItemData(13, type=ItemClassification.progression),
    "Mathematics":          CivVItemData(14, type=ItemClassification.progression),
    "Construction":         CivVItemData(15, type=ItemClassification.progression),
    "Philosophy":           CivVItemData(16, type=ItemClassification.progression),
    "Drama":                CivVItemData(17, type=ItemClassification.progression),
    "Currency":             CivVItemData(18, type=ItemClassification.progression),
    "Engineering":          CivVItemData(19, type=ItemClassification.progression),
    "Iron Working":         CivVItemData(20, type=ItemClassification.progression),
    "Theology":             CivVItemData(21, type=ItemClassification.progression),
    "Civil Service":        CivVItemData(22, type=ItemClassification.progression),
    "Guilds":               CivVItemData(23, type=ItemClassification.progression),
    "Metal Casting":        CivVItemData(24, type=ItemClassification.progression),
    "Compass":              CivVItemData(25, type=ItemClassification.progression),
    "Education":            CivVItemData(26, type=ItemClassification.progression),
    "Chivalry":             CivVItemData(27, type=ItemClassification.progression),
    "Machinery":            CivVItemData(28, type=ItemClassification.progression),
    "Physics":              CivVItemData(29, type=ItemClassification.progression),
    "Steel":                CivVItemData(30, type=ItemClassification.progression),
    "Astronomy":            CivVItemData(31, type=ItemClassification.progression),
    "Acoustics":            CivVItemData(32, type=ItemClassification.progression),
    "Banking":              CivVItemData(33, type=ItemClassification.progression),
    "Printing Press":       CivVItemData(34, type=ItemClassification.progression),
    "Gunpowder":            CivVItemData(35, type=ItemClassification.progression),
    "Navigation":           CivVItemData(36, type=ItemClassification.progression),
    "Architecture":         CivVItemData(37, type=ItemClassification.progression),
    "Economics":            CivVItemData(38, type=ItemClassification.progression),
    "Metallurgy":           CivVItemData(39, type=ItemClassification.progression),
    "Chemistry":            CivVItemData(40, type=ItemClassification.progression),
    "Archaeology":          CivVItemData(41, type=ItemClassification.progression),
    "Scientific Theory":    CivVItemData(42, type=ItemClassification.progression),
    "Industrialization":    CivVItemData(43, type=ItemClassification.progression),
    "Rifling":              CivVItemData(44, type=ItemClassification.progression),
    "Military Science":     CivVItemData(45, type=ItemClassification.progression),
    "Fertilizer":           CivVItemData(46, type=ItemClassification.progression),
    "Biology":              CivVItemData(47, type=ItemClassification.progression),
    "Electricity":          CivVItemData(48, type=ItemClassification.progression),
    "Steam Power":          CivVItemData(49, type=ItemClassification.progression),
    "Dynamite":             CivVItemData(50, type=ItemClassification.progression),
    "Refrigeration":        CivVItemData(51, type=ItemClassification.progression),
    "Radio":                CivVItemData(52, type=ItemClassification.progression),
    "Replaceable Parts":    CivVItemData(53, type=ItemClassification.progression),
    "Flight":               CivVItemData(54, type=ItemClassification.progression),
    "Railroad":             CivVItemData(55, type=ItemClassification.progression),
    "Plastics":             CivVItemData(56, type=ItemClassification.progression),
    "Electronics":          CivVItemData(57, type=ItemClassification.progression),
    "Ballistics":           CivVItemData(58, type=ItemClassification.progression),
    "Combustion":           CivVItemData(59, type=ItemClassification.progression),
    "Penicillin":           CivVItemData(60, type=ItemClassification.progression),
    "Atomic Theory":        CivVItemData(61, type=ItemClassification.progression),
    "Radar":                CivVItemData(62, type=ItemClassification.progression),
    "Combined Arms":        CivVItemData(63, type=ItemClassification.progression),
    "Ecology":              CivVItemData(64, type=ItemClassification.progression),
    "Nuclear Fission":      CivVItemData(65, type=ItemClassification.progression),
    "Rocketry":             CivVItemData(66, type=ItemClassification.progression),
    "Computers":            CivVItemData(67, type=ItemClassification.progression),
    "Telecommunications":   CivVItemData(68, type=ItemClassification.progression),
    "Mobile Tactics":       CivVItemData(69, type=ItemClassification.progression),
    "Advanced Ballistics":  CivVItemData(70, type=ItemClassification.progression),
    "Satellites":           CivVItemData(71, type=ItemClassification.progression),
    "Robotics":             CivVItemData(72, type=ItemClassification.progression),
    "Lasers":               CivVItemData(73, type=ItemClassification.progression),
    "The Internet":         CivVItemData(74, type=ItemClassification.progression),
    "Globalization":        CivVItemData(75, type=ItemClassification.progression),
    "Particle Physics":     CivVItemData(76, type=ItemClassification.progression),
    "Nuclear Fusion":      CivVItemData(77, type=ItemClassification.progression),
    "Nanotechnology":       CivVItemData(78, type=ItemClassification.progression),
    "Stealth":              CivVItemData(79, type=ItemClassification.progression)
}